#ifndef _CAL_H    /* Guard against multiple inclusion */
#define _CAL_H

/* Provide C++ Compatibility */
#ifdef __cplusplus
extern "C" {
#endif
    
#define GLITCH_B1   10
#define GLITCH_B2   10
#define GLITCH_B3   10
#define GLITCH_B4   10
#define GLITCH_B5   10
#define GLITCH_B6   10
    

int8_t coefGlitch[64] = {
    0,

    (GLITCH_B1),

    (GLITCH_B2),
    (GLITCH_B2+GLITCH_B1),

    (GLITCH_B3),
    (GLITCH_B3+GLITCH_B1),
    (GLITCH_B3+GLITCH_B2),
    (GLITCH_B3+GLITCH_B2+GLITCH_B1),

    (GLITCH_B4),
    (GLITCH_B4+GLITCH_B1),
    (GLITCH_B4+GLITCH_B2),
    (GLITCH_B4+GLITCH_B1+GLITCH_B2),
    (GLITCH_B4+GLITCH_B3),
    (GLITCH_B4+GLITCH_B3+GLITCH_B1),
    (GLITCH_B4+GLITCH_B3+GLITCH_B2),
    (GLITCH_B4+GLITCH_B3+GLITCH_B2+GLITCH_B1),

    (GLITCH_B5),
    (GLITCH_B5+GLITCH_B1),
    (GLITCH_B5+GLITCH_B2),
    (GLITCH_B5+GLITCH_B1+GLITCH_B2),
    (GLITCH_B5+GLITCH_B3),
    (GLITCH_B5+GLITCH_B3+GLITCH_B1),
    (GLITCH_B5+GLITCH_B3+GLITCH_B2),
    (GLITCH_B5+GLITCH_B3+GLITCH_B2+GLITCH_B1),
    (GLITCH_B5+GLITCH_B4),
    (GLITCH_B5+GLITCH_B4+GLITCH_B1),
    (GLITCH_B5+GLITCH_B4+GLITCH_B2),
    (GLITCH_B5+GLITCH_B4+GLITCH_B2+GLITCH_B1),
    (GLITCH_B5+GLITCH_B4+GLITCH_B3),
    (GLITCH_B5+GLITCH_B4+GLITCH_B3+GLITCH_B1),
    (GLITCH_B5+GLITCH_B4+GLITCH_B3+GLITCH_B2),
    (GLITCH_B5+GLITCH_B4+GLITCH_B3+GLITCH_B2+GLITCH_B1),

    (GLITCH_B6),
    (GLITCH_B6+GLITCH_B1),
    (GLITCH_B6+GLITCH_B2),
    (GLITCH_B6+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B3),
    (GLITCH_B6+GLITCH_B3+GLITCH_B1),
    (GLITCH_B6+GLITCH_B3+GLITCH_B2),
    (GLITCH_B6+GLITCH_B3+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B4),
    (GLITCH_B6+GLITCH_B4+GLITCH_B1),
    (GLITCH_B6+GLITCH_B4+GLITCH_B2),
    (GLITCH_B6+GLITCH_B4+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B4+GLITCH_B3),
    (GLITCH_B6+GLITCH_B4+GLITCH_B3+GLITCH_B1),
    (GLITCH_B6+GLITCH_B4+GLITCH_B3+GLITCH_B2),
    (GLITCH_B6+GLITCH_B4+GLITCH_B3+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5),
    (GLITCH_B6+GLITCH_B5+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B2),
    (GLITCH_B6+GLITCH_B5+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B3),
    (GLITCH_B6+GLITCH_B5+GLITCH_B3+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B3+GLITCH_B2),
    (GLITCH_B6+GLITCH_B5+GLITCH_B3+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B2),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B2+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B3),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B3+GLITCH_B1),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B3+GLITCH_B2),
    (GLITCH_B6+GLITCH_B5+GLITCH_B4+GLITCH_B3+GLITCH_B2+GLITCH_B1)
};
    
    
    
    
    
    



/* Provide C++ Compatibility */
#ifdef __cplusplus
}
#endif

#endif /* _CAL_H */

/* *****************************************************************************
 End of File
 */
